{
   "ResponseMetadata":{
      "RequestId":"5BWW0FY2SRNFT3MC",
      "HostId":"q/5p2KyXaSUFN+pUWiLXEZdriE7lBdb24cDpKi+PC8V8u6MEqdhtUkC2DeyuI/nxeF2ytMShptQ=",
      "HTTPStatusCode":200,
      "HTTPHeaders":{
         "x-amz-id-2":"q/5p2KyXaSUFN+pUWiLXEZdriE7lBdb24cDpKi+PC8V8u6MEqdhtUkC2DeyuI/nxeF2ytMShptQ=",
         "x-amz-request-id":"5BWW0FY2SRNFT3MC",
         "date":"Mon, 04 Nov 2024 10:59:50 GMT",
         "content-type":"application/xml",
         "transfer-encoding":"chunked",
         "server":"AmazonS3"
      },
      "RetryAttempts":0
   },
   "Buckets":[
      {
         "Name":"amit-s3demo",
         "CreationDate":datetime.datetime(2024,
         8,
         18,
         10,
         44,
         33,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"amit-terraformbackend",
         "CreationDate":datetime.datetime(2024,
         10,
         15,
         6,
         34,
         18,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"amplify-webpush-dev-133237-deployment",
         "CreationDate":datetime.datetime(2022,
         6,
         16,
         13,
         32,
         45,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"atin-s3-source",
         "CreationDate":datetime.datetime(2023,
         11,
         17,
         11,
         11,
         32,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"automatedcloudwatchdashbo-cwtagpipelineartifactsbu-ic5mc2k5pemf",
         "CreationDate":datetime.datetime(2024,
         8,
         30,
         7,
         7,
         11,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"aws-athena-query-results-ap-south-1-570646387953",
         "CreationDate":datetime.datetime(2024,
         3,
         12,
         11,
         20,
         22,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"aws-athena-query-results-cid-570646387953-ap-south-1",
         "CreationDate":datetime.datetime(2024,
         3,
         12,
         11,
         20,
         33,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"aws-athena-query-results-cid-570646387953-us-east-1",
         "CreationDate":datetime.datetime(2024,
         4,
         5,
         10,
         17,
         9,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"aws-athena-query-results-us-east-1-570646387953",
         "CreationDate":datetime.datetime(2023,
         5,
         30,
         7,
         41,
         35,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"aws-cloudtrail-logs-570646387953-48f7d737",
         "CreationDate":datetime.datetime(2024,
         9,
         12,
         9,
         46,
         38,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"aws-cloudtrail-logs-570646387953-8666e8cb",
         "CreationDate":datetime.datetime(2021,
         12,
         17,
         8,
         45,
         24,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"aws-cloudtrail-logs-570646387953-a07318c4",
         "CreationDate":datetime.datetime(2024,
         9,
         13,
         11,
         45,
         51,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"aws-sam-cli-managed-default-samclisourcebucket-ugi9zebbhcww",
         "CreationDate":datetime.datetime(2024,
         8,
         8,
         7,
         40,
         42,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"aws-security-data-lake-ap-south-1-whg5myvab4exkkh0f3vykvcrsxp48",
         "CreationDate":datetime.datetime(2024,
         8,
         13,
         11,
         7,
         12,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"aws-security-data-lake-us-east-1-xbmoesrihndgbfzxaktjdlzhfy5o3c",
         "CreationDate":datetime.datetime(2024,
         8,
         13,
         11,
         6,
         57,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"aws-waf-logs-ccoe-rcs",
         "CreationDate":datetime.datetime(2023,
         8,
         3,
         7,
         54,
         44,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"ccoe-cudos-poc-split",
         "CreationDate":datetime.datetime(2023,
         6,
         27,
         14,
         46,
         3,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"ccoe-ocr-doc-bucket",
         "CreationDate":datetime.datetime(2024,
         8,
         8,
         7,
         42,
         38,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"ccoe-ocr-queue-bucket",
         "CreationDate":datetime.datetime(2024,
         8,
         8,
         7,
         42,
         59,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"ccoe-ocr-stage-bucket",
         "CreationDate":datetime.datetime(2024,
         8,
         8,
         7,
         42,
         33,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"ccoe-qs-cur",
         "CreationDate":datetime.datetime(2023,
         11,
         29,
         6,
         51,
         24,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"ccoe-rcs-cid-cur3",
         "CreationDate":datetime.datetime(2023,
         7,
         17,
         11,
         46,
         40,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"cdk-hnb659fds-assets-570646387953-ap-south-1",
         "CreationDate":datetime.datetime(2023,
         11,
         20,
         6,
         6,
         57,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"cdk-hnb659fds-assets-570646387953-us-east-1",
         "CreationDate":datetime.datetime(2024,
         4,
         5,
         14,
         15,
         20,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"cf-templates-bhxbqx7r6njf-ap-south-1",
         "CreationDate":datetime.datetime(2021,
         12,
         21,
         11,
         48,
         22,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"cf-templates-bhxbqx7r6njf-ap-south-2",
         "CreationDate":datetime.datetime(2024,
         8,
         26,
         5,
         34,
         50,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"cf-templates-bhxbqx7r6njf-ap-southeast-1",
         "CreationDate":datetime.datetime(2023,
         7,
         19,
         9,
         25,
         39,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"cf-templates-bhxbqx7r6njf-eu-west-1",
         "CreationDate":datetime.datetime(2023,
         3,
         29,
         6,
         54,
         44,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"cf-templates-bhxbqx7r6njf-us-east-1",
         "CreationDate":datetime.datetime(2021,
         5,
         9,
         10,
         33,
         14,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"cf-templates-bhxbqx7r6njf-us-east-2",
         "CreationDate":datetime.datetime(2021,
         12,
         15,
         6,
         14,
         14,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"cf-templates-bhxbqx7r6njf-us-west-1",
         "CreationDate":datetime.datetime(2021,
         12,
         29,
         6,
         43,
         44,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"cf-templates-bhxbqx7r6njf-us-west-2",
         "CreationDate":datetime.datetime(2021,
         10,
         7,
         10,
         5,
         37,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"cf-templates-bhxbqx7r6njf0-us-east-1",
         "CreationDate":datetime.datetime(2024,
         7,
         22,
         7,
         5,
         54,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"cf-templates-bhxbqx7r6njf0-us-west-2",
         "CreationDate":datetime.datetime(2024,
         9,
         12,
         7,
         57,
         21,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"codebuild-buildspec-steampipeline",
         "CreationDate":datetime.datetime(2023,
         11,
         29,
         8,
         33,
         37,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"codepipeline-ap-south-1-241317946859",
         "CreationDate":datetime.datetime(2023,
         11,
         21,
         10,
         23,
         2,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"codepipeline-us-east-1-770033161470",
         "CreationDate":datetime.datetime(2024,
         3,
         3,
         2,
         13,
         19,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"codepipeline-us-west-1-383665948345",
         "CreationDate":datetime.datetime(2024,
         3,
         27,
         18,
         20,
         27,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"codepipeline-us-west-2-857115921555",
         "CreationDate":datetime.datetime(2024,
         9,
         18,
         6,
         47,
         21,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"coe-bucket-tests-backup",
         "CreationDate":datetime.datetime(2024,
         10,
         22,
         10,
         25,
         51,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"coe-bucket-tests-california",
         "CreationDate":datetime.datetime(2024,
         10,
         22,
         9,
         34,
         40,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"coe-bucket-tests-nvir",
         "CreationDate":datetime.datetime(2024,
         10,
         22,
         9,
         33,
         19,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"coe-rapyder-solutions",
         "CreationDate":datetime.datetime(2023,
         2,
         28,
         7,
         47,
         49,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"coe-rapyder-solutions-bahrain",
         "CreationDate":datetime.datetime(2024,
         9,
         23,
         10,
         52,
         56,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"coe-rapyder-solutions-california",
         "CreationDate":datetime.datetime(2024,
         5,
         6,
         9,
         40,
         50,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"coe-rapyder-solutions-frankfurt",
         "CreationDate":datetime.datetime(2024,
         5,
         30,
         7,
         27,
         52,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"coe-rapyder-solutions-ireland",
         "CreationDate":datetime.datetime(2024,
         9,
         12,
         13,
         41,
         27,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"coe-rapyder-solutions-mumbai",
         "CreationDate":datetime.datetime(2023,
         9,
         15,
         5,
         23,
         28,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"coe-rapyder-solutions-ohio",
         "CreationDate":datetime.datetime(2023,
         9,
         15,
         5,
         22,
         30,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"coe-rapyder-solutions-oregon",
         "CreationDate":datetime.datetime(2024,
         4,
         30,
         5,
         24,
         45,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"coe-rapyder-solutions-singapore",
         "CreationDate":datetime.datetime(2023,
         9,
         15,
         5,
         24,
         11,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"config-bucket-570646387953",
         "CreationDate":datetime.datetime(2021,
         6,
         11,
         14,
         15,
         7,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"download.elcom.digitall",
         "CreationDate":datetime.datetime(2021,
         9,
         27,
         5,
         17,
         24,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"elasticbeanstalk-us-east-1-570646387953",
         "CreationDate":datetime.datetime(2024,
         3,
         27,
         17,
         32,
         30,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"elasticbeanstalk-us-west-1-570646387953",
         "CreationDate":datetime.datetime(2024,
         3,
         20,
         16,
         55,
         21,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"elb-logs-570646387953",
         "CreationDate":datetime.datetime(2023,
         6,
         1,
         5,
         57,
         49,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"forman-s3-vpc-flow-logs",
         "CreationDate":datetime.datetime(2024,
         5,
         27,
         9,
         5,
         33,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"harden-test-config-570646387953-logs",
         "CreationDate":datetime.datetime(2024,
         8,
         26,
         5,
         47,
         2,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"imgtransformationstack-s3sampleoriginalimagebucket-inpl8qpeouxa",
         "CreationDate":datetime.datetime(2023,
         11,
         20,
         6,
         17,
         4,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"imgtransformationstack-s3samplewebsitebucket187dc4-9y0vrhxls1i8",
         "CreationDate":datetime.datetime(2023,
         11,
         20,
         6,
         17,
         4,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"imgtransformationstack-s3transformedimagebucket6d8-skhxrlypnjff",
         "CreationDate":datetime.datetime(2023,
         11,
         20,
         6,
         17,
         4,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"intelli-agent-apiconstructllmbotdocumentsfc4f8a7a-es3lvpmecvyd",
         "CreationDate":datetime.datetime(2024,
         8,
         13,
         7,
         39,
         19,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"intelli-agent-etlstacknes-llmbotgluelibbucketd023f-qczeq3qf8y3l",
         "CreationDate":datetime.datetime(2024,
         8,
         13,
         7,
         31,
         53,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"intelli-agent-etlstacknes-llmbotglueresultbucket79-h6kc0ukhh2vk",
         "CreationDate":datetime.datetime(2024,
         8,
         13,
         7,
         31,
         53,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"intelli-agent-models-570646387953-us-east-1",
         "CreationDate":datetime.datetime(2024,
         8,
         13,
         6,
         53,
         13,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"intelli-agent-uiconstructuicloudfrontloggingbucket-zpuy5i4bfqxj",
         "CreationDate":datetime.datetime(2024,
         8,
         13,
         7,
         8,
         36,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"intelli-agent-uiconstructuis3bucket14677a01-qr09xbaj0b1c",
         "CreationDate":datetime.datetime(2024,
         8,
         13,
         7,
         8,
         52,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"intelli-agent-uiconstructuis3loggingbucketdb4a02bd-fjjtmht7bszh",
         "CreationDate":datetime.datetime(2024,
         8,
         13,
         7,
         8,
         37,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"lambdasam-dae909b622-ap-south-1",
         "CreationDate":datetime.datetime(2023,
         12,
         12,
         7,
         45,
         38,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"logs-for-security-hub-remediate",
         "CreationDate":datetime.datetime(2022,
         2,
         4,
         11,
         29,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"logsforsecurityhubremediate-s3",
         "CreationDate":datetime.datetime(2022,
         2,
         10,
         5,
         12,
         6,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"opencost-poc-bucket",
         "CreationDate":datetime.datetime(2024,
         5,
         15,
         7,
         8,
         35,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"pca-inputbucket-client2",
         "CreationDate":datetime.datetime(2022,
         7,
         5,
         9,
         32,
         39,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"pca-inputbucket-client5",
         "CreationDate":datetime.datetime(2022,
         7,
         28,
         5,
         42,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"pca-outputbucket-client1",
         "CreationDate":datetime.datetime(2022,
         7,
         5,
         9,
         34,
         8,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"pca-outputbucket-client2",
         "CreationDate":datetime.datetime(2022,
         7,
         5,
         9,
         52,
         10,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"pca-outputbucket-client5",
         "CreationDate":datetime.datetime(2022,
         7,
         28,
         5,
         43,
         33,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"postcallanalysistemplates",
         "CreationDate":datetime.datetime(2023,
         1,
         18,
         10,
         19,
         4,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"postcallanalytics-bulkuploadbucket-1mr34ee0ugf7i",
         "CreationDate":datetime.datetime(2022,
         6,
         29,
         9,
         44,
         16,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"postcallanalytics-inputbucket-1dre81x8yrz69",
         "CreationDate":datetime.datetime(2022,
         6,
         29,
         9,
         44,
         16,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"postcallanalytics-outputbucket-s8uq93op7o5e",
         "CreationDate":datetime.datetime(2022,
         6,
         29,
         9,
         44,
         17,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"postcallanalytics-pcaui-1w4vsul3ocxxc-w-logbucket-1qua56u2je8qr",
         "CreationDate":datetime.datetime(2022,
         6,
         29,
         9,
         44,
         54,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"postcallanalytics-pcaui-1w4vsul3ocxxc-w-webbucket-ll4cf5ummfhc",
         "CreationDate":datetime.datetime(2022,
         6,
         29,
         9,
         44,
         54,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"postcallanalytics-supportfilesbucket-un6cuqa8nvzw",
         "CreationDate":datetime.datetime(2022,
         6,
         29,
         9,
         44,
         16,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"rapyder-coe-solutions",
         "CreationDate":datetime.datetime(2022,
         3,
         2,
         8,
         19,
         12,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"rapyder-compliance-backup-report-570646387953",
         "CreationDate":datetime.datetime(2024,
         8,
         5,
         10,
         42,
         12,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"rapyder-compliance-reports-1-570646387953",
         "CreationDate":datetime.datetime(2023,
         12,
         27,
         10,
         25,
         28,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"rapyder-restricted-solutions",
         "CreationDate":datetime.datetime(2022,
         12,
         23,
         11,
         6,
         47,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"rapyder-visitor-management-portal",
         "CreationDate":datetime.datetime(2023,
         3,
         28,
         9,
         38,
         38,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"rbl-dev-serverlessdeploymentbucket-19089uyu2f2xb",
         "CreationDate":datetime.datetime(2022,
         7,
         5,
         9,
         0,
         26,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"rbl-test-records-bucket-5463167498",
         "CreationDate":datetime.datetime(2024,
         2,
         1,
         6,
         34,
         6,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"rcs-ccoe-logs-vpc-alb",
         "CreationDate":datetime.datetime(2023,
         5,
         29,
         14,
         21,
         58,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"rcs-immersion-sec",
         "CreationDate":datetime.datetime(2021,
         11,
         16,
         10,
         41,
         36,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"rcs-patch-logs",
         "CreationDate":datetime.datetime(2022,
         4,
         21,
         10,
         27,
         52,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"sagemaker-studio-570646387953-1pfqz2qaxr9",
         "CreationDate":datetime.datetime(2024,
         8,
         9,
         8,
         36,
         21,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"sagemaker-studio-570646387953-uzfm5jnyl0p",
         "CreationDate":datetime.datetime(2024,
         8,
         9,
         8,
         36,
         25,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"sagemaker-us-east-1-570646387953",
         "CreationDate":datetime.datetime(2024,
         8,
         9,
         8,
         36,
         25,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"sam-test-pinpoint",
         "CreationDate":datetime.datetime(2023,
         5,
         30,
         5,
         48,
         12,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"sameer886744",
         "CreationDate":datetime.datetime(2021,
         5,
         3,
         10,
         26,
         39,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"select-demo",
         "CreationDate":datetime.datetime(2022,
         4,
         7,
         5,
         44,
         44,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"shahid-csvtodynamo",
         "CreationDate":datetime.datetime(2021,
         10,
         14,
         11,
         49,
         7,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"shahid-temp-dnd",
         "CreationDate":datetime.datetime(2024,
         6,
         16,
         7,
         44,
         48,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"so0050-0ed2ee7c688b-570646387953-us-east-1-ingest",
         "CreationDate":datetime.datetime(2024,
         7,
         26,
         7,
         9,
         36,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"so0050-0ed2ee7c688b-570646387953-us-east-1-logs",
         "CreationDate":datetime.datetime(2024,
         7,
         26,
         7,
         9,
         21,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"so0050-0ed2ee7c688b-570646387953-us-east-1-proxy",
         "CreationDate":datetime.datetime(2024,
         7,
         26,
         7,
         9,
         36,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"so0050-0ed2ee7c688b-570646387953-us-east-1-web",
         "CreationDate":datetime.datetime(2024,
         7,
         26,
         7,
         9,
         36,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"stackset-api-infrastruct-pipelinebuiltartifactbuc-zzdoluv8lm1o",
         "CreationDate":datetime.datetime(2023,
         4,
         14,
         9,
         38,
         25,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"tallyexes",
         "CreationDate":datetime.datetime(2021,
         6,
         20,
         10,
         21,
         15,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"terraform-state-files-eks-automation",
         "CreationDate":datetime.datetime(2023,
         11,
         8,
         6,
         1,
         43,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"testing-waters-codebuild",
         "CreationDate":datetime.datetime(2024,
         9,
         18,
         7,
         26,
         54,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"testing-waters-codebuild-nvirginia",
         "CreationDate":datetime.datetime(2024,
         9,
         18,
         7,
         50,
         27,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"testinguswest2testing",
         "CreationDate":datetime.datetime(2024,
         1,
         11,
         5,
         40,
         11,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"veeam-backup-ccoe",
         "CreationDate":datetime.datetime(2024,
         3,
         14,
         10,
         37,
         31,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"velero-terraform",
         "CreationDate":datetime.datetime(2023,
         10,
         28,
         17,
         50,
         17,
         "tzinfo=tzlocal())"
      },
      {
         "Name":"www.formwebsite.com",
         "CreationDate":datetime.datetime(2021,
         10,
         20,
         9,
         10,
         32,
         "tzinfo=tzlocal())"
      }
   ],
   "Owner":{
      "DisplayName":"aws.internal.coe",
      "ID":"e491f16b759771e2ae89e564eda9b260798de8ce8f8fb84fb97c89a7e37428cd"
   }
}